"""Fix role id from str to int

Revision ID: 13c025f29af2
Revises: d6fd8fe1bd61
Create Date: 2023-10-29 02:57:14.599173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13c025f29af2'
down_revision: Union[str, None] = 'd6fd8fe1bd61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
